[[constraint]]
  branch = "master"
  name = "github.com/Pallinder/go-randomdata"

[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jeromedoucet/route"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[override]]
  branch = "master"
  name = "github.com/docker/distribution"
