[[constraint]]
  branch = "master"
  name = "github.com/Pallinder/go-randomdata"

[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/jeromedoucet/route"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"

[prune]
  go-tests = true
  unused-packages = true
